# dependabot configuration 

version: 2
updates:
# configuration for go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
        update-type : "semver: minor"

# configuration for docker 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"