name: Lint Workflow

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Semgrep Static Analysis    
      uses: returntocorp/semgrep-action@v1
      with:
       config: "p/default"

    - name: Hadolint Dockerfile Analysis  
      uses: hadolint/hadolint-action@v3.1.0
      with:
       dockerfile: Dockerfile

    - name: Super Linter For Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      uses: github/super-linter/slim@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 