name: Test Workflow 

on:
  push:

jobs:
  test_workflow:
    strategy:
      matrix:
        go_versions: [1.17, 1.18, 1.19]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Go ${{ matrix.go_versions }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_versions }}

    - name: Run tests
      run: go test ./...